In [139]:
import numpy as np
import pandas as pd

In [140]:
movies=pd.read_csv('tmdb_5000_credits.csv')
credits=pd.read_csv('tmdb_5000_movies.csv')

In [141]:
movies.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [142]:
credits.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [143]:
# merge both data set to single data of movies using title
movies=movies.merge(credits,on='title')

In [144]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   movie_id              4809 non-null   int64
 1   title                 4809 non-null   object
 2   cast                  4809 non-null   object
 3   crew                  4809 non-null   object
 4   budget                4809 non-null   int64
 5   genres                4809 non-null   object
 6   homepage              1713 non-null   object
 7   id                    4809 non-null   int64
 8   keywords              4809 non-null   object
 9   original_language     4809 non-null   object
 10  original_title        4809 non-null   object
 11  overview              4806 non-null   object
 12  popularity            4809 non-null   float64
 13  production_companies  4809 non-null   object
 14  production_countries  4809 non-null   object
 15  release_date          4808 non-null   object
 16  revenue               4809 non-null   int64
 17  runtime               4807 non-null   float64
 18  spoken_languages      4809 non-null   object
 19  status                4809 non-null   object
 20  tagline               3965 non-null   object
 21  vote_average          4809 non-null   float64
 22  vote_count            4809 non-null   int64
dtypes: float64(3), int64(5), object(15)
memory usage: 864.2+ KB

In [145]:
#what column to keep for content based recommender system
movies=movies[['movie_id','cast','crew','genres','keywords','overview','title']]

In [146]:
movies.head()

,movie_id,cast,crew,genres,keywords,overview,title
0,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...",Avatar
1,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End
2,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bondâ€™s past sends him o...,Spectre
3,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...","[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...,The Dark Knight Rises
4,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca...",John Carter

In [147]:
#check missing data
movies.isnull().sum()

movie_id    0
cast        0
crew        0
genres      0
keywords    0
overview    3
title       0
dtype: int64

In [148]:
#drop null values row
movies.dropna(inplace=True)

In [149]:
#check for duplicate values
movies.duplicated().sum()

0

In [150]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [151]:
#convert obj object from str to list
import ast

def convert(obj):
    l=[]
    for i in ast.literal_eval(obj):
        l.append(i['name'])
    return l

In [152]:
movies['genres'] = movies['genres'].apply(convert)

In [153]:
movies.head()

,movie_id,cast,crew,genres,keywords,overview,title
0,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...",Avatar
1,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End
2,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...","[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bondâ€™s past sends him o...,Spectre
3,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...","[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...,The Dark Knight Rises
4,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca...",John Carter

In [154]:
#apply similar to keyword column
movies['keywords'] = movies['keywords'].apply(convert)

In [155]:
movies['cast'][0]    # or movies.iloc[0].cast

'[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'

In [156]:
def convert3(obj):
    count=0
    for i in ast.literal_eval(obj):
        if count!=3:
            l.append(l['name'])
        else:
            break
    return l

In [157]:
movies['cast'] = movies['cast'].apply(convert)

In [158]:
movies.head()

,movie_id,cast,crew,genres,keywords,overview,title
0,19995,"[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...",Avatar
1,285,"[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End
2,206647,"[Daniel Craig, Christoph Waltz, LÃ©a Seydoux, R...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bondâ€™s past sends him o...,Spectre
3,49026,"[Christian Bale, Michael Caine, Gary Oldman, A...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,The Dark Knight Rises
4,49529,"[Taylor Kitsch, Lynn Collins, Samantha Morton,...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","John Carter is a war-weary, former military ca...",John Carter

In [159]:
def fetch_director(obj):
    l=[]
    for i in ast.literal_eval(obj):
        if i['job']=='Director' :
            l.append(i['name'])
            break
            
            
    return l

In [160]:
movies['crew']=movies['crew'].apply(fetch_director)

In [161]:
movies.head()

,movie_id,cast,crew,genres,keywords,overview,title
0,19995,"[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron],"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...",Avatar
1,285,"[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski],"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End
2,206647,"[Daniel Craig, Christoph Waltz, LÃ©a Seydoux, R...",[Sam Mendes],"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bondâ€™s past sends him o...,Spectre
3,49026,"[Christian Bale, Michael Caine, Gary Oldman, A...",[Christopher Nolan],"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,The Dark Knight Rises
4,49529,"[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[Andrew Stanton],"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","John Carter is a war-weary, former military ca...",John Carter

In [162]:
# overviw column is str so we convert it to list by applying lamda function so that we can cocatenate it with other columns
movies['overview']=movies['overview'].apply(lambda x: x.split())

In [163]:
movies.head()

,movie_id,cast,crew,genres,keywords,overview,title
0,19995,"[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron],"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[In, the, 22nd, century,, a, paraplegic, Marin...",Avatar
1,285,"[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski],"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Captain, Barbossa,, long, believed, to, be, d...",Pirates of the Caribbean: At World's End
2,206647,"[Daniel Craig, Christoph Waltz, LÃ©a Seydoux, R...",[Sam Mendes],"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[A, cryptic, message, from, Bondâ€™s, past, send...",Spectre
3,49026,"[Christian Bale, Michael Caine, Gary Oldman, A...",[Christopher Nolan],"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Following, the, death, of, District, Attorney...",The Dark Knight Rises
4,49529,"[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[Andrew Stanton],"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[John, Carter, is, a, war-weary,, former, mili...",John Carter

In [164]:
# we will reove space ex: space war--> spacewar , bcoz space can also be interpreted as space colon or other space releated words
movies['cast']=movies['cast'].apply(lambda x: [i.replace(' ','') for i in x])
movies['keywords']=movies['keywords'].apply(lambda x: [i.replace(' ','') for i in x])
movies['crew']=movies['crew'].apply(lambda x: [i.replace(' ','') for i in x])
movies['overview']=movies['overview'].apply(lambda x: [i.replace(' ','') for i in x])
movies['genres']=movies['genres'].apply(lambda x: [i.replace(' ','') for i in x])

In [165]:
movies['tags']=movies['overview']+movies['genres']+movies['keywords']+movies['cast']+movies['crew']

In [166]:
movies.head()

,movie_id,cast,crew,genres,keywords,overview,title,tags
0,19995,"[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron],"[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[In, the, 22nd, century,, a, paraplegic, Marin...",Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,"[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski],"[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[Captain, Barbossa,, long, believed, to, be, d...",Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,"[DanielCraig, ChristophWaltz, LÃ©aSeydoux, Ralp...",[SamMendes],"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[A, cryptic, message, from, Bondâ€™s, past, send...",Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,"[ChristianBale, MichaelCaine, GaryOldman, Anne...",[ChristopherNolan],"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[Following, the, death, of, District, Attorney...",The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,"[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton],"[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[John, Carter, is, a, war-weary,, former, mili...",John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [167]:
new_df=movies[['movie_id','title','tags']]

In [168]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [169]:
new_df['tags']=new_df['tags'].apply(lambda x: ' '.join(x))

C:\Users\nitin\AppData\Local\Temp\ipykernel_34164\4076496393.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x: ' '.join(x))

In [170]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [171]:
#convert to lower case
new_df['tags'].apply(lambda x: x.lower())

0       in the 22nd century, a paraplegic marine is di...
1       captain barbossa, long believed to be dead, ha...
2       a cryptic message from bondâ€™s past sends him o...
3       following the death of district attorney harve...
4       john carter is a war-weary, former military ca...
                              ...
4804    el mariachi just wants to play his guitar and ...
4805    a newlywed couple's honeymoon is upended by th...
4806    "signed, sealed, delivered" introduces a dedic...
4807    when ambitious new york attorney sam is sent t...
4808    ever since the second grade when he first saw ...
Name: tags, Length: 4806, dtype: object

In [172]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000,stop_words='english')
vectors = cv.fit_transform(new_df['tags']).toarray() #converted every movie to vector

In [173]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zoo', 'zooeydeschanel', 'zoÃ«kravitz'],
      dtype=object)

In [174]:
import nltk

In [175]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [176]:
def stem(text):
    l=[]
    for i in text.split():      #split function will convert string to list and we will iterate over it to get each word
        l.append(ps.stem(i))
        
    return ' '.join(l)        #convert list to string

In [177]:
new_df['tags'].apply(stem)

0       in the 22nd century, a parapleg marin is dispa...
1       captain barbossa, long believ to be dead, ha c...
2       a cryptic messag from bondâ€™ past send him on a...
3       follow the death of district attorney harvey d...
4       john carter is a war-weary, former militari ca...
                              ...
4804    el mariachi just want to play hi guitar and ca...
4805    a newlyw couple' honeymoon is upend by the arr...
4806    "signed, sealed, delivered" introduc a dedic q...
4807    when ambiti new york attorney sam is sent to s...
4808    ever sinc the second grade when he first saw h...
Name: tags, Length: 4806, dtype: object

In [178]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vectors)

In [179]:
similarity[0]

array([1.        , 0.07142857, 0.05216405, ..., 0.02326211, 0.02571722,
       0.        ])

In [180]:
new_df[new_df['title']=='Batman Begins'].index[0]

119

In [181]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])

[(0, 1.0000000000000002),
 (1920, 0.23473823893078552),
 (1216, 0.23294541397390256),
 (582, 0.2309782890611944),
 (539, 0.2252817784447915),
 (507, 0.21912524504463887),
 (1444, 0.21398024625545647),
 (3608, 0.21398024625545647),
 (4192, 0.2123976976214366),
 (260, 0.21170244960998524),
 (74, 0.20935894733965596),
 (83, 0.20256711147285467),
 (2971, 0.19839002137983244),
 (3730, 0.19738550848793068),
 (495, 0.1930468356263361),
 (2333, 0.19258222162991084),
 (322, 0.1904761904761905),
 (61, 0.1889822365046136),
 (1204, 0.18824832213400472),
 (36, 0.1860968420796942),
 (2409, 0.18609684207969418),
 (1194, 0.1852396434087371),
 (1537, 0.18523964340873708),
 (974, 0.18257418583505539),
 (2204, 0.18257418583505539),
 (3538, 0.18257418583505536),
 (3327, 0.18184824186332701),
 (2786, 0.18156825980064073),
 (972, 0.1800205749557739),
 (4405, 0.17817416127494962),
 (1321, 0.17699808135119716),
 (47, 0.17699808135119713),
 (4048, 0.17636890537566463),
 (1329, 0.17496355305594127),
 (942, 0.17295817388759027),
 (151, 0.17251638983558856),
 (3162, 0.1711841970043652),
 (2999, 0.17118419700436519),
 (184, 0.17078251276599332),
 (466, 0.1690308509457033),
 (2731, 0.1683587574253685),
 (150, 0.16718346377260584),
 (27, 0.1649572197684645),
 (305, 0.1648119469795901),
 (461, 0.16448792373994225),
 (220, 0.16366341767699427),
 (1344, 0.16366341767699427),
 (301, 0.16143660075018942),
 (1275, 0.16116459280507608),
 (4, 0.16101529717988267),
 (158, 0.15936381457791915),
 (1673, 0.15936381457791915),
 (581, 0.157485197087178),
 (931, 0.15649215928719035),
 (1071, 0.15590239111558093),
 (300, 0.1559023911155809),
 (4010, 0.1543033499620919),
 (46, 0.15275252316519466),
 (1201, 0.1522038868295523),
 (661, 0.15194743527951726),
 (373, 0.15130688316720062),
 (1396, 0.151247535495505),
 (1831, 0.151247535495505),
 (838, 0.14969623771302396),
 (3354, 0.14847846772912465),
 (3622, 0.14824986333222023),
 (108, 0.1469861839480328),
 (1945, 0.14638501094227999),
 (208, 0.1454785934906616),
 (502, 0.14458880781356395),
 (2496, 0.1432670637653132),
 (2515, 0.1432670637653132),
 (3628, 0.1432670637653132),
 (1383, 0.14285714285714288),
 (4336, 0.14285714285714288),
 (56, 0.14085904245475275),
 (1965, 0.14062009564580388),
 (149, 0.13977131156292244),
 (168, 0.13957263155977065),
 (1808, 0.13957263155977065),
 (2075, 0.13856849886842332),
 (2169, 0.13856849886842332),
 (7, 0.13829563644637993),
 (1355, 0.13801311186847084),
 (1220, 0.136504726557987),
 (1938, 0.136504726557987),
 (1178, 0.13638618139749523),
 (1488, 0.13468700594029479),
 (2970, 0.13468700594029479),
 (139, 0.13397282541141675),
 (67, 0.13363062095621223),
 (91, 0.13231403100624078),
 (332, 0.13231403100624078),
 (577, 0.13231403100624078),
 (2686, 0.13231403100624078),
 (26, 0.13226001425322162),
 (311, 0.13226001425322162),
 (84, 0.13195808169029696),
 (490, 0.1315903389919538),
 (1327, 0.1315903389919538),
 (3999, 0.1315903389919538),
 (1297, 0.13093073414159542),
 (1322, 0.13093073414159542),
 (31, 0.13041013273932528),
 (17, 0.130031582934249),
 (2584, 0.1286978904175574),
 (568, 0.12858612496840993),
 (687, 0.12858612496840993),
 (1299, 0.12858612496840993),
 (2133, 0.1271711710197892),
 (41, 0.12598815766974242),
 (422, 0.12598815766974242),
 (487, 0.12598815766974242),
 (2620, 0.12598815766974242),
 (206, 0.1259881576697424),
 (557, 0.12515654358043973),
 (3409, 0.12515654358043973),
 (2873, 0.12483755678647186),
 (127, 0.12389865694583801),
 (1715, 0.12371791482634838),
 (413, 0.1235415527768502),
 (595, 0.1235415527768502),
 (505, 0.12344267996967354),
 (4490, 0.12344267996967354),
 (342, 0.12309149097933272),
 (157, 0.12104550653376049),
 (1047, 0.12104550653376049),
 (1747, 0.12104550653376049),
 (3675, 0.12049067317796998),
 (199, 0.11952286093343936),
 (2480, 0.11952286093343936),
 (454, 0.11904761904761905),
 (1037, 0.11904761904761905),
 (368, 0.11878277418329973),
 (2378, 0.11878277418329973),
 (111, 0.11765520133375293),
 (187, 0.11765520133375293),
 (3407, 0.11765520133375293),
 (1741, 0.11757927025044307),
 (172, 0.11664236870396086),
 (939, 0.11664236870396086),
 (1658, 0.11664236870396086),
 (1002, 0.11664236870396084),
 (4203, 0.11572751247156893),
 (4348, 0.11572751247156893),
 (94, 0.11501092655705904),
 (1015, 0.11501092655705904),
 (1617, 0.11501092655705904),
 (2713, 0.11501092655705904),
 (2868, 0.11461365101225056),
 (4673, 0.11461365101225056),
 (238, 0.11396057645963795),
 (228, 0.11375393879832252),
 (420, 0.11375393879832252),
 (249, 0.1126872339638022),
 (1833, 0.1126872339638022),
 (3376, 0.1126872339638022),
 (549, 0.11253728415158593),
 (740, 0.11253728415158593),
 (123, 0.11135885079684352),
 (1832, 0.11135885079684352),
 (3309, 0.11135885079684352),
 (3630, 0.11135885079684352),
 (432, 0.1113588507968435),
 (50, 0.11085479909473867),
 (3147, 0.11065666703449763),
 (270, 0.11021667854435137),
 (2547, 0.11021667854435135),
 (3663, 0.10910894511799621),
 (778, 0.1091089451179962),
 (1277, 0.1091089451179962),
 (43, 0.10910894511799618),
 (134, 0.10910894511799618),
 (1031, 0.10910894511799618),
 (1096, 0.10910894511799618),
 (1274, 0.10910894511799618),
 (1512, 0.10910894511799618),
 (4097, 0.10910894511799618),
 (232, 0.10744306187005072),
 (859, 0.10744306187005072),
 (52, 0.10699012312772824),
 (95, 0.10699012312772824),
 (1479, 0.10699012312772824),
 (1574, 0.1061988488107183),
 (1301, 0.10619884881071828),
 (1373, 0.10619884881071828),
 (2634, 0.10619884881071828),
 (4545, 0.10597597584982435),
 (28, 0.10585122480499262),
 (148, 0.10585122480499262),
 (544, 0.10585122480499262),
 (1273, 0.10585122480499262),
 (2439, 0.104990131391452),
 (81, 0.10482848367219183),
 (483, 0.10432810619146021),
 (2450, 0.10432810619146021),
 (2583, 0.10432810619146021),
 (3498, 0.10432810619146021),
 (4079, 0.10432810619146021),
 (425, 0.10403129732205989),
 (2760, 0.10403129732205989),
 (3781, 0.10350983390135314),
 (627, 0.10350983390135313),
 (653, 0.10350983390135313),
 (808, 0.10350983390135313),
 (2521, 0.10350983390135313),
 (3721, 0.10350983390135313),
 (4000, 0.10350983390135313),
 (239, 0.10309826235529032),
 (10, 0.10286889997472794),
 (87, 0.10286889997472794),
 (88, 0.10286889997472794),
 (160, 0.10286889997472794),
 (275, 0.10286889997472794),
 (746, 0.10286889997472794),
 (1294, 0.10286889997472794),
 (1982, 0.10286889997472794),
 (777, 0.10218988991416098),
 (1019, 0.10218988991416098),
 (294, 0.10146925788636821),
 (579, 0.10146925788636821),
 (2072, 0.10146925788636821),
 (3102, 0.10146925788636821),
 (3620, 0.10146925788636821),
 (102, 0.10130511230913847),
 (692, 0.10130511230913847),
 (141, 0.10101525445522108),
 (1156, 0.10101525445522108),
 (2762, 0.10101525445522108),
 (4018, 0.10101525445522108),
 (4198, 0.10101525445522108),
 (18, 0.10044292546128848),
 (166, 0.10012523486435178),
 (1290, 0.10012523486435178),
 (1401, 0.10012523486435178),
 (2181, 0.10012523486435178),
 (3340, 0.10012523486435178),
 (169, 0.09960238411119947),
 (2106, 0.09960238411119947),
 (68, 0.09883324222148016),
 (122, 0.09883324222148016),
 (266, 0.09883324222148016),
 (754, 0.09883324222148016),
 (854, 0.09883324222148016),
 (900, 0.09883324222148016),
 (988, 0.09883324222148016),
 (1175, 0.09883324222148016),
 (193, 0.09878259746169996),
 (773, 0.09869275424396534),
 (1524, 0.09869275424396534),
 (1721, 0.09869275424396534),
 (2259, 0.09869275424396534),
 (2323, 0.09869275424396534),
 (3839, 0.09869275424396534),
 (4331, 0.09869275424396534),
 (4623, 0.09869275424396534),
 (203, 0.09759000729485333),
 (312, 0.09759000729485333),
 (535, 0.09759000729485333),
 (787, 0.09759000729485333),
 (1082, 0.09759000729485333),
 (1109, 0.09759000729485333),
 (2013, 0.09759000729485333),
 (3783, 0.09759000729485333),
 (4230, 0.09759000729485333),
 (213, 0.09720197391996738),
 (1727, 0.09652341781316803),
 (2661, 0.09652341781316803),
 (513, 0.09639253854237598),
 (1086, 0.09639253854237598),
 (1158, 0.09639253854237598),
 (1195, 0.09639253854237598),
 (153, 0.09569487529386911),
 (72, 0.09523809523809525),
 (131, 0.09523809523809525),
 (1202, 0.09523809523809525),
 (1823, 0.09523809523809525),
 (3008, 0.09523809523809525),
 (3443, 0.09523809523809525),
 (3464, 0.09523809523809525),
 (2596, 0.09523809523809523),
 (624, 0.09449111825230681),
 (660, 0.09449111825230681),
 (1575, 0.09449111825230681),
 (2651, 0.09449111825230681),
 (3055, 0.09449111825230681),
 (3736, 0.09449111825230681),
 (14, 0.09412416106700235),
 (174, 0.09412416106700235),
 (334, 0.09412416106700235),
 (510, 0.09412416106700235),
 (295, 0.09412416106700233),
 (371, 0.09304842103984709),
 (529, 0.09304842103984709),
 (1056, 0.09304842103984709),
 (2388, 0.09304842103984709),
 (3140, 0.09304842103984709),
 (3093, 0.09258200997725516),
 (3954, 0.09258200997725516),
 (4256, 0.09258200997725516),
 (403, 0.09221388919541469),
 (785, 0.09221388919541468),
 (85, 0.09212254307176114),
 (307, 0.09212254307176114),
 (5, 0.09156219276643894),
 (410, 0.09100315103865801),
 (508, 0.09100315103865801),
 (898, 0.09100315103865801),
 (1846, 0.09100315103865801),
 (1924, 0.09100315103865801),
 (715, 0.09078412990032037),
 (1077, 0.09078412990032037),
 (1501, 0.09078412990032037),
 (1589, 0.09078412990032037),
 (1686, 0.09078412990032037),
 (2456, 0.09078412990032037),
 (2562, 0.09078412990032037),
 (2652, 0.09078412990032037),
 (4135, 0.09078412990032037),
 (126, 0.09002982732126874),
 (933, 0.09002982732126874),
 (1233, 0.09002982732126874),
 (257, 0.08908708063747481),
 (278, 0.08908708063747481),
 (330, 0.08908708063747481),
 (643, 0.08908708063747481),
 (2284, 0.08908708063747481),
 (2796, 0.08908708063747481),
 (4045, 0.08908708063747481),
 (4641, 0.08908708063747481),
 (4654, 0.08908708063747481),
 (476, 0.0890870806374748),
 (479, 0.0890870806374748),
 (794, 0.0890870806374748),
 (922, 0.0890870806374748),
 (1280, 0.0890870806374748),
 (1408, 0.0890870806374748),
 (2660, 0.0890870806374748),
 (1089, 0.08849904067559858),
 (279, 0.08817334283548109),
 (412, 0.08817334283548109),
 (870, 0.08817334283548109),
 (564, 0.08748177652797065),
 (791, 0.08748177652797065),
 (937, 0.08748177652797065),
 (1306, 0.08748177652797065),
 (2396, 0.08748177652797065),
 (3297, 0.08748177652797065),
 (4468, 0.08748177652797065),
 (182, 0.08728715609439695),
 (596, 0.08728715609439695),
 (813, 0.08728715609439695),
 (1030, 0.08728715609439695),
 (1357, 0.08642716314028859),
 (45, 0.08642716314028857),
 (129, 0.08642716314028857),
 (589, 0.08642716314028857),
 (997, 0.08642716314028857),
 (1278, 0.08642716314028857),
 (799, 0.08625819491779428),
 (292, 0.08596023825918792),
 (369, 0.08596023825918792),
 (389, 0.08596023825918792),
 (786, 0.08596023825918792),
 (935, 0.08596023825918792),
 (1474, 0.08596023825918792),
 (2093, 0.08596023825918792),
 (2247, 0.08596023825918792),
 (2817, 0.08596023825918792),
 (2840, 0.08596023825918792),
 (253, 0.08559209850218259),
 (1439, 0.08559209850218259),
 (2274, 0.08559209850218259),
 (2488, 0.08559209850218259),
 (4516, 0.08559209850218259),
 (467, 0.08478078067985947),
 (607, 0.08478078067985947),
 (2003, 0.08478078067985947),
 (2005, 0.08478078067985947),
 (142, 0.08451542547285165),
 (167, 0.08451542547285165),
 (306, 0.08451542547285165),
 (356, 0.08451542547285165),
 (400, 0.08451542547285165),
 (960, 0.08451542547285165),
 (1756, 0.08451542547285165),
 (3428, 0.08451542547285165),
 (3537, 0.08451542547285165),
 (4626, 0.08451542547285165),
 (107, 0.0839921051131616),
 (222, 0.0839921051131616),
 (473, 0.0839921051131616),
 (243, 0.08322503785764791),
 (612, 0.08322503785764791),
 (2968, 0.08322503785764791),
 (233, 0.083141099321054),
 (315, 0.083141099321054),
 (781, 0.083141099321054),
 (901, 0.083141099321054),
 (1004, 0.083141099321054),
 (1586, 0.083141099321054),
 (2167, 0.083141099321054),
 (3816, 0.083141099321054),
 (3926, 0.083141099321054),
 (4259, 0.083141099321054),
 (92, 0.08247860988423225),
 (491, 0.08247860988423225),
 (1276, 0.08247860988423225),
 (3154, 0.08247860988423225),
 (3218, 0.08247860988423225),
 (4353, 0.08247860988423225),
 (4737, 0.08247860988423225),
 (164, 0.08183170883849714),
 (920, 0.08183170883849714),
 (1378, 0.08183170883849714),
 (1523, 0.08183170883849714),
 (1560, 0.08183170883849714),
 (1700, 0.08183170883849714),
 (4657, 0.08183170883849714),
 (618, 0.08175191193132877),
 (1496, 0.08175191193132877),
 (1497, 0.08175191193132877),
 (1878, 0.08175191193132877),
 (2099, 0.08175191193132877),
 (1418, 0.08104408984731078),
 (1487, 0.08104408984731078),
 (3441, 0.08104408984731078),
 (75, 0.08058229640253804),
 (263, 0.08058229640253804),
 (349, 0.08058229640253804),
 (511, 0.08058229640253804),
 (691, 0.08058229640253804),
 (980, 0.08058229640253804),
 (1790, 0.08058229640253804),
 (2251, 0.08058229640253804),
 (2253, 0.08058229640253804),
 (2794, 0.08058229640253804),
 (3028, 0.08058229640253804),
 (3235, 0.08058229640253804),
 (3301, 0.08058229640253804),
 (3310, 0.08058229640253804),
 (3423, 0.08058229640253804),
 (3910, 0.08058229640253804),
 (2448, 0.08043618151097337),
 (2498, 0.08035434036903079),
 (2386, 0.08000256012288656),
 (103, 0.07968190728895957),
 (170, 0.07968190728895957),
 (768, 0.07968190728895957),
 (1828, 0.07968190728895957),
 (2880, 0.07968190728895957),
 (3253, 0.07968190728895957),
 (3431, 0.07968190728895957),
 (3949, 0.07968190728895957),
 (4061, 0.07968190728895957),
 (4492, 0.07968190728895957),
 (4502, 0.07968190728895957),
 (35, 0.07938841860374446),
 (236, 0.07938841860374446),
 (241, 0.07938841860374446),
 (271, 0.07938841860374446),
 (325, 0.07938841860374446),
 (530, 0.07938841860374446),
 (775, 0.07938841860374446),
 (814, 0.07938841860374446),
 (1142, 0.07938841860374446),
 (1207, 0.07938841860374446),
 (1249, 0.07938841860374446),
 (2644, 0.07938841860374446),
 (812, 0.07902607796935997),
 (1282, 0.07902607796935997),
 (1346, 0.07902607796935997),
 (1405, 0.07902607796935997),
 (1898, 0.07902607796935997),
 (230, 0.07838618016696206),
 (1639, 0.07838618016696206),
 (23, 0.07824607964359516),
 (112, 0.07824607964359516),
 (207, 0.07824607964359516),
 (227, 0.07824607964359516),
 (894, 0.07824607964359516),
 (1614, 0.07824607964359516),
 (1616, 0.07824607964359516),
 (2304, 0.07824607964359516),
 (51, 0.0777615791359739),
 (63, 0.0777615791359739),
 (363, 0.0777615791359739),
 (12, 0.07715167498104596),
 (21, 0.07715167498104596),
 (32, 0.07715167498104596),
 (33, 0.07715167498104596),
 (634, 0.07715167498104596),
 (654, 0.07715167498104596),
 (1027, 0.07715167498104596),
 (1139, 0.07715167498104596),
 (1534, 0.07715167498104596),
 (2175, 0.07715167498104596),
 (2354, 0.07715167498104596),
 (2801, 0.07715167498104596),
 (2856, 0.07715167498104596),
 (3155, 0.07715167498104596),
 (3470, 0.07715167498104596),
 (3527, 0.07715167498104596),
 (4431, 0.07715167498104596),
 (4718, 0.07715167498104596),
 (19, 0.07655590023509529),
 (501, 0.07655590023509529),
 (572, 0.07655590023509529),
 (1926, 0.07655590023509529),
 (96, 0.07610194341477616),
 (214, 0.07610194341477616),
 (242, 0.07610194341477616),
 (680, 0.07610194341477616),
 (1113, 0.07610194341477616),
 (1942, 0.07610194341477616),
 (2527, 0.07610194341477616),
 (2851, 0.07610194341477616),
 (987, 0.07610194341477615),
 (59, 0.07597371763975863),
 (2763, 0.07540461810874112),
 (125, 0.07529232524210427),
 (245, 0.07509392614826384),
 (587, 0.07509392614826384),
 (752, 0.07509392614826384),
 (885, 0.07509392614826384),
 (899, 0.07509392614826384),
 (1161, 0.07509392614826384),
 (1181, 0.07509392614826384),
 (1473, 0.07509392614826384),
 (2683, 0.07509392614826384),
 (2820, 0.07509392614826384),
 (3206, 0.07509392614826384),
 (3355, 0.07509392614826384),
 (3701, 0.07509392614826384),
 (4083, 0.07509392614826384),
 (313, 0.07484811885651198),
 (2165, 0.07484811885651198),
 (2410, 0.07484811885651198),
 (2712, 0.07484811885651198),
 (2789, 0.07484811885651198),
 (274, 0.07458533939516852),
 (71, 0.07412493166611012),
 (98, 0.07412493166611012),
 (457, 0.07412493166611012),
 (1011, 0.07412493166611012),
 (1269, 0.07412493166611012),
 (1367, 0.07412493166611012),
 (2018, 0.07412493166611012),
 (3389, 0.07412493166611012),
 (2203, 0.07324975421315115),
 (70, 0.07319250547113999),
 (97, 0.07319250547113999),
 (223, 0.07319250547113999),
 (547, 0.07319250547113999),
 (632, 0.07319250547113999),
 (788, 0.07319250547113999),
 (2163, 0.07319250547113999),
 (2235, 0.07319250547113999),
 (3059, 0.07319250547113999),
 (4055, 0.07319250547113999),
 (4123, 0.07319250547113999),
 (4451, 0.07319250547113999),
 (415, 0.0727392967453308),
 (1288, 0.0727392967453308),
 (2250, 0.0727392967453308),
 (3069, 0.0727392967453308),
 (3832, 0.0727392967453308),
 (4165, 0.0727392967453308),
 (11, 0.07229440390678199),
 (39, 0.07229440390678199),
 (105, 0.07229440390678199),
 (185, 0.07229440390678199),
 (362, 0.07229440390678199),
 (472, 0.07229440390678199),
 (503, 0.07229440390678199),
 (543, 0.07229440390678199),
 (827, 0.07229440390678199),
 (2592, 0.07229440390678199),
 (2650, 0.07229440390678199),
 (3022, 0.07229440390678199),
 (3091, 0.07229440390678199),
 (3907, 0.07229440390678199),
 (4205, 0.07229440390678199),
 (4640, 0.07229440390678199),
 (190, 0.07174960033341753),
 (1, 0.07142857142857144),
 (53, 0.07142857142857144),
 (138, 0.07142857142857144),
 (1032, 0.07142857142857144),
 (2395, 0.07142857142857144),
 (2701, 0.07142857142857144),
 (3255, 0.07142857142857144),
 (3449, 0.07142857142857144),
 (3806, 0.07142857142857144),
 (4180, 0.07142857142857144),
 (381, 0.07079923254047886),
 (2882, 0.07079923254047886),
 (3374, 0.07079923254047886),
 (4412, 0.07079923254047886),
 (4473, 0.07079923254047886),
 (37, 0.07059312080025176),
 (212, 0.07059312080025176),
 (626, 0.07059312080025176),
 (1145, 0.07059312080025176),
 (1634, 0.06988565578146122),
 (82, 0.06978631577988531),
 (1289, 0.06978631577988531),
 (1325, 0.06978631577988531),
 (1446, 0.06978631577988531),
 (1883, 0.06978631577988531),
 (2052, 0.06978631577988531),
 (2241, 0.06978631577988531),
 (2264, 0.06978631577988531),
 (2467, 0.06978631577988531),
 (2831, 0.06978631577988531),
 (2916, 0.06978631577988531),
 (3822, 0.06978631577988531),
 (55, 0.06944193284588147),
 (229, 0.06944193284588147),
 (205, 0.06900655593423542),
 (471, 0.06900655593423542),
 (534, 0.06900655593423542),
 (536, 0.06900655593423542),
 (665, 0.06900655593423542),
 (671, 0.06900655593423542),
 (732, 0.06900655593423542),
 (908, 0.06900655593423542),
 (1005, 0.06900655593423542),
 (1348, 0.06900655593423542),
 (1621, 0.06900655593423542),
 (1623, 0.06900655593423542),
 (1632, 0.06900655593423542),
 (1664, 0.06900655593423542),
 (1765, 0.06900655593423542),
 (1770, 0.06900655593423542),
 (2021, 0.06900655593423542),
 (2787, 0.06900655593423542),
 (3398, 0.06900655593423542),
 (3982, 0.06900655593423542),
 (3994, 0.06900655593423542),
 (4181, 0.06900655593423542),
 (728, 0.0682523632789935),
 (782, 0.0682523632789935),
 (3188, 0.0682523632789935),
 (4538, 0.0682523632789935),
 (488, 0.06774797209007694),
 (101, 0.06752237049095156),
 (121, 0.06752237049095156),
 (132, 0.06752237049095156),
 (254, 0.06752237049095156),
 (979, 0.06752237049095156),
 (1146, 0.06752237049095156),
 (1701, 0.06752237049095156),
 (2056, 0.06752237049095156),
 (2135, 0.06752237049095156),
 (2363, 0.06752237049095156),
 (2888, 0.06752237049095156),
 (3000, 0.06752237049095156),
 (4343, 0.06752237049095156),
 (109, 0.06734350297014739),
 (384, 0.06734350297014739),
 (776, 0.06734350297014739),
 (1323, 0.06734350297014739),
 (1655, 0.06734350297014739),
 (2659, 0.06734350297014739),
 (3671, 0.06734350297014739),
 (3931, 0.06734350297014739),
 (4099, 0.06734350297014739),
 (4216, 0.06734350297014739),
 (4403, 0.06734350297014739),
 (4568, 0.06734350297014739),
 (4638, 0.06734350297014739),
 (657, 0.06694619270045785),
 (1990, 0.06694619270045785),
 (86, 0.0668153104781061),
 (1191, 0.0668153104781061),
 (1455, 0.0668153104781061),
 (2372, 0.0668153104781061),
 (3390, 0.0668153104781061),
 (3212, 0.06664889599684098),
 (183, 0.06617222226472869),
 (76, 0.06613000712661082),

In [201]:
new_df.iloc[1920].title

'Lifeforce'

In [191]:
def recommend(movie):
    movie_index = new_df[new_df['title']==movie].index[0] # for index of movie
    distance = similarity[movie_index]
    movie_list=sorted(list(enumerate(distance)),reverse=True,key=lambda x:x[1])[1:6]   # lambda is used to get 1st element for sorting
    for i in movie_list:
        print(new_df.iloc[i[0]].title)          #i[0] is index of the movie

In [192]:
recommend('Avatar')

Lifeforce
Aliens vs Predator: Requiem
Battle: Los Angeles
Titan A.E.
Independence Day

In [195]:
import pickle

In [196]:
pickle.dump(new_df,open('movies.pkl','wb'))

In [198]:
new_df['title'].values

array(['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre',
       ..., 'Signed, Sealed, Delivered', 'Shanghai Calling',
       'My Date with Drew'], dtype=object)

In [199]:
pickle.dump(similarity,open('similarirty.pkl','wb'))

In [200]:
similarity[112]

array([0.07824608, 0.05216405, 0.05714286, ..., 0.07644708, 0.02817181,
       0.        ])